apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "billing-platform.fullname" . }}-worker
  labels:
    {{- include "billing-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.replicaCount.worker }}
  selector:
    matchLabels:
      {{- include "billing-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "billing-platform.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      {{- include "billing-platform.podSecurityContext" . | nindent 6 }}
      containers:
        - name: worker
          {{- include "billing-platform.containerSecurityContext" . | nindent 10 }}
          image: {{ include "billing-platform.image" (list . .Values.image.tags.worker) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - celery
            - -A
            - billing_platform.workers.celery_app
            - worker
            - --loglevel=info
            - -Q
            - {{ .Values.worker.queue }}
          envFrom:
            - configMapRef:
                name: {{ include "billing-platform.configMapName" . }}
            - secretRef:
                name: {{ include "billing-platform.secretName" . }}
          {{- include "billing-platform.workerLivenessProbe" . | nindent 10 }}
          {{- include "billing-platform.workerReadinessProbe" . | nindent 10 }}
