#!/usr/bin/env python3
"""Prod-like multi-tenant seed for demos/load tests — docs/perf/README.md."""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
from dataclasses import dataclass, field
from datetime import UTC, datetime, timedelta
from pathlib import Path

from seed_prod_like_catalog import CatalogContext, ensure_prod_like_catalog
from seed_prod_like_profiles import (
    PROFILES,
    ProdLikeProfile,
    external_subscription_id,
    invoice_paid_org_indices,
    org_idempotency_key,
    sub_idempotency_key,
    subscriptions_count_for_org,
    usage_idempotency_key,
    usage_quantity,
)
from seed_prod_like_purge import purge_prod_like_prefix
from seed_prod_like_recon import seed_recon_mismatch_org
from seed_prod_like_status import StatusBucket, plan_key_for_org, status_bucket_for_org
from seed_prod_like_webhooks import (
    apply_invoice_paid_webhook,
    apply_payment_failed_webhook,
    ensure_mock_stripe_invoice,
    resolve_mock_stripe_base_url,
)
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

from billing_platform.config import Settings, get_settings
from billing_platform.domain.models.api_key import ApiKeyRole
from billing_platform.domain.models.organization import Organization
from billing_platform.domain.models.plan import Plan
from billing_platform.domain.models.subscription import Subscription
from billing_platform.services.api_keys import create_api_key
from billing_platform.services.grace import enforce_grace_expiry
from billing_platform.services.organizations import create_organization
from billing_platform.services.period_close import close_billing_period
from billing_platform.services.subscriptions import cancel_subscription, create_subscription
from billing_platform.services.usage import (
    UsageEventIn,
    aggregate_pending_hours,
    ingest_usage_batch,
)

MANIFEST_PATH = Path(".local/seed-prod-like-output.json")
K6_ENV_PATH = Path(".local/k6-multi-keys.env")

PRODUCT_FEATURE_KEY = "api_calls"


@dataclass
class OrgManifest:
    public_id: str
    external_id: str
    org_idx: int
    subscription_public_ids: list[str] = field(default_factory=list)
    api_key_ids: dict[str, str] = field(default_factory=dict)
    product_service_raw_key: str | None = None


@dataclass
class SeedResult:
    profile: str
    organization_count: int
    recon_organization_count: int
    organization_count_total: int
    usage_events_accepted: int
    usage_events_duplicates: int
    recon_invoice_ids: list[str]
    manifest_path: str
    organizations: list[OrgManifest]
    platform_admin_key_ids: list[str] = field(default_factory=list)
    platform_admin_keys: list[str] = field(default_factory=list)
    catalog_plan_keys: list[str] = field(default_factory=list)


def _load_manifest() -> dict[str, object]:
    if MANIFEST_PATH.is_file():
        return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    return {}


def _write_manifest(payload: dict[str, object]) -> None:
    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST_PATH.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def _write_k6_env(sample_keys: list[dict[str, str]]) -> None:
    K6_ENV_PATH.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# generated by seed_prod_like.py — do not commit"]
    for idx, entry in enumerate(sample_keys):
        lines.append(f"K6_ORG_ID_{idx}={entry['org_public_id']}")
        lines.append(f"K6_API_KEY_{idx}={entry['raw_key']}")
    K6_ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


async def _ensure_platform_admin_keys(
    session: AsyncSession,
    profile: ProdLikeProfile,
    existing_manifest: dict[str, object],
) -> tuple[list[str], list[str], list[str]]:
    """Return (key_ids, raw_keys_new_this_run, all_raw_keys_for_manifest)."""
    stored_ids = existing_manifest.get("platform_admin_key_ids")
    stored_keys = existing_manifest.get("platform_admin_keys")
    key_ids: list[str] = []
    raw_keys: list[str] = []
    created_now: list[str] = []

    if isinstance(stored_ids, list) and isinstance(stored_keys, list):
        for kid, raw in zip(stored_ids, stored_keys, strict=False):
            if isinstance(kid, str) and isinstance(raw, str):
                key_ids.append(kid)
                raw_keys.append(raw)

    while len(key_ids) < profile.platform_admin_keys:
        api_key, raw = await create_api_key(
            session,
            organization_id=None,
            role=ApiKeyRole.PLATFORM_ADMIN.value,
        )
        key_ids.append(str(api_key.id))
        raw_keys.append(raw)
        created_now.append(raw)

    return key_ids, created_now, raw_keys


async def _set_external_subscription_id(
    session: AsyncSession,
    subscription: Subscription,
    ext_id: str,
) -> None:
    if subscription.external_subscription_id != ext_id:
        subscription.external_subscription_id = ext_id
        await session.flush()


async def _apply_status_bucket(
    session: AsyncSession,
    settings: Settings,
    *,
    org_idx: int,
    subscription: Subscription,
    bucket: StatusBucket,
    plan: Plan,
) -> None:
    ext_id = external_subscription_id(org_idx, 0)
    await _set_external_subscription_id(session, subscription, ext_id)

    if bucket == StatusBucket.trialing:
        return

    if bucket == StatusBucket.incomplete:
        return

    invoice_id = f"in_pl_{org_idx:04d}_activate"
    await ensure_mock_stripe_invoice(
        settings,
        invoice_id=invoice_id,
        amount_cents=2900,
        external_subscription_id=ext_id,
    )

    if bucket in (
        StatusBucket.active,
        StatusBucket.past_due,
        StatusBucket.unpaid,
        StatusBucket.cancel_at_period_end,
    ):
        await apply_invoice_paid_webhook(
            session,
            org_idx=org_idx,
            subscription=subscription,
            invoice_id=invoice_id,
        )
        await session.refresh(subscription)

    if bucket == StatusBucket.past_due:
        await apply_payment_failed_webhook(session, org_idx=org_idx, subscription=subscription)
        await session.refresh(subscription)

    if bucket == StatusBucket.canceled:
        if subscription.status != "canceled":
            await cancel_subscription(session, subscription, at_period_end=False)
        return

    if bucket == StatusBucket.unpaid:
        await apply_payment_failed_webhook(
            session,
            org_idx=org_idx,
            subscription=subscription,
            event_kind="unpaid",
        )
        await session.refresh(subscription)
        grace_days = plan.grace_period_days or 7
        subscription.past_due_entered_at = datetime.now(UTC) - timedelta(days=grace_days + 1)
        await session.flush()
        await enforce_grace_expiry(session, now=datetime.now(UTC))
        await session.refresh(subscription)
        return

    if bucket == StatusBucket.cancel_at_period_end:
        await cancel_subscription(session, subscription, at_period_end=True)


async def _seed_organization(
    session: AsyncSession,
    settings: Settings,
    profile: ProdLikeProfile,
    catalog: CatalogContext,
    org_idx: int,
) -> OrgManifest:
    org = await create_organization(
        session,
        name=f"PL Org {org_idx:04d}",
        external_id=f"ext_pl_{org_idx:04d}",
        idempotency_key=org_idempotency_key(org_idx),
        billing_email=f"billing-{org_idx:04d}@prod-like.example.com",
        metadata={
            "seed_slice": "prod_like",
            "profile": profile.name,
            "org_idx": org_idx,
        },
    )
    bucket = status_bucket_for_org(org_idx, profile)
    plan_key = plan_key_for_org(org_idx, profile, bucket)
    plan = catalog.plans[plan_key]
    sub_count = subscriptions_count_for_org(org_idx, profile)
    sub_public_ids: list[str] = []
    primary_sub: Subscription | None = None

    for sub_slot in range(sub_count):
        sub = await create_subscription(
            session,
            organization_id=org.id,
            plan_id=plan.id,
            idempotency_key=sub_idempotency_key(org_idx, sub_slot),
            metadata={"seed_slice": "prod_like", "org_idx": org_idx, "sub_slot": sub_slot},
        )
        ext_id = external_subscription_id(org_idx, sub_slot)
        await _set_external_subscription_id(session, sub, ext_id)
        sub_public_ids.append(str(sub.public_id))
        if sub_slot == 0:
            primary_sub = sub

    assert primary_sub is not None
    await _apply_status_bucket(
        session,
        settings,
        org_idx=org_idx,
        subscription=primary_sub,
        bucket=bucket,
        plan=plan,
    )

    api_key_ids: dict[str, str] = {}
    product_raw: str | None = None
    for role, count in profile.api_keys_per_org.items():
        for _ in range(count):
            api_key, raw = await create_api_key(
                session,
                organization_id=org.id,
                role=role,
            )
            api_key_ids[role] = str(api_key.id)
            if role == ApiKeyRole.PRODUCT_SERVICE.value:
                product_raw = raw

    return OrgManifest(
        public_id=str(org.public_id),
        external_id=org.external_id or "",
        org_idx=org_idx,
        subscription_public_ids=sub_public_ids,
        api_key_ids=api_key_ids,
        product_service_raw_key=product_raw,
    )


async def _seed_usage(
    session: AsyncSession,
    profile: ProdLikeProfile,
    org_by_idx: dict[int, Organization],
) -> tuple[int, int]:
    total = profile.usage_events_total
    base_per_org = total // profile.organizations
    remainder = total % profile.organizations
    now = datetime.now(UTC)
    window_start = now - timedelta(days=60)
    accepted = 0
    duplicates = 0
    global_seq = 0

    for org_idx in range(profile.organizations):
        org = org_by_idx[org_idx]
        event_count = base_per_org + (1 if org_idx < remainder else 0)
        batch: list[UsageEventIn] = []
        for _local_seq in range(event_count):
            seq = global_seq
            global_seq += 1
            offset_seconds = (seq * 37) % int((now - window_start).total_seconds() or 1)
            recorded_at = window_start + timedelta(seconds=offset_seconds)
            batch.append(
                UsageEventIn(
                    feature_key=PRODUCT_FEATURE_KEY,
                    quantity=usage_quantity(org_idx, seq),
                    idempotency_key=usage_idempotency_key(org_idx, seq),
                    recorded_at=recorded_at,
                )
            )
            if len(batch) >= profile.usage_batch_size:
                result = await ingest_usage_batch(
                    session,
                    organization_id=org.id,
                    events=batch,
                )
                accepted += result.accepted
                duplicates += result.duplicates
                batch = []
        if batch:
            result = await ingest_usage_batch(session, organization_id=org.id, events=batch)
            accepted += result.accepted
            duplicates += result.duplicates

    return accepted, duplicates


async def _seed_period_closes(
    session: AsyncSession,
    profile: ProdLikeProfile,
    org_by_idx: dict[int, Organization],
) -> None:
    """Close prior calendar month for invoice-paid fraction orgs (usage.period_closed outbox)."""
    now = datetime.now(UTC)
    period_end = now.replace(day=1, hour=0, minute=0, second=0, microsecond=0) - timedelta(
        seconds=1
    )
    period_start = period_end.replace(day=1, hour=0, minute=0, second=0, microsecond=0)

    await aggregate_pending_hours(session, now=now)

    for org_idx in invoice_paid_org_indices(profile):
        org = org_by_idx.get(org_idx)
        if org is None:
            continue
        if profile.name == "full" and org_idx % 2 != 0:
            continue
        await close_billing_period(
            session,
            organization_id=org.id,
            period_start=period_start,
            period_end=period_end,
            idempotency_key=f"pl_period_{org_idx:04d}_m1",
        )


async def run_prod_like_seed(
    session: AsyncSession,
    settings: Settings,
    profile: ProdLikeProfile,
) -> SeedResult:
    """Core seed orchestration (callable from tests)."""
    existing_manifest = _load_manifest()
    catalog = await ensure_prod_like_catalog(session, profile)
    admin_ids, _created, admin_raws = await _ensure_platform_admin_keys(
        session, profile, existing_manifest
    )

    org_manifests: list[OrgManifest] = []
    org_by_idx: dict[int, Organization] = {}

    for org_idx in range(profile.organizations):
        manifest_entry = await _seed_organization(session, settings, profile, catalog, org_idx)
        org_manifests.append(manifest_entry)
        result = await session.execute(
            select(Organization).where(Organization.public_id == manifest_entry.public_id)
        )
        org = result.scalar_one()
        org_by_idx[org_idx] = org

    usage_accepted, usage_duplicates = await _seed_usage(session, profile, org_by_idx)
    await _seed_period_closes(session, profile, org_by_idx)

    recon_ids: list[str] = []
    for recon_idx in range(profile.recon_discrepancy_orgs):
        invoice_id = await seed_recon_mismatch_org(session, settings, recon_idx)
        recon_ids.append(invoice_id)

    return SeedResult(
        profile=profile.name,
        organization_count=profile.organizations,
        recon_organization_count=profile.recon_discrepancy_orgs,
        organization_count_total=profile.organizations + profile.recon_discrepancy_orgs,
        usage_events_accepted=usage_accepted,
        usage_events_duplicates=usage_duplicates,
        recon_invoice_ids=recon_ids,
        manifest_path=str(MANIFEST_PATH),
        organizations=org_manifests,
        platform_admin_key_ids=admin_ids,
        platform_admin_keys=admin_raws,
        catalog_plan_keys=sorted(catalog.plans.keys()),
    )


def _result_to_manifest(result: SeedResult, *, seeded_at: str) -> dict[str, object]:
    sample_k6: list[dict[str, str]] = []
    for entry in result.organizations[:10]:
        if entry.product_service_raw_key:
            sample_k6.append(
                {
                    "org_public_id": entry.public_id,
                    "raw_key": entry.product_service_raw_key,
                    "role": ApiKeyRole.PRODUCT_SERVICE.value,
                }
            )

    return {
        "profile": result.profile,
        "seeded_at": seeded_at,
        "marker": "prod_like",
        "organization_count": result.organization_count,
        "recon_organization_count": result.recon_organization_count,
        "organization_count_total": result.organization_count_total,
        "organizations": [
            {
                "public_id": o.public_id,
                "external_id": o.external_id,
                "org_idx": o.org_idx,
                "subscription_public_ids": o.subscription_public_ids,
                "api_key_ids": o.api_key_ids,
            }
            for o in result.organizations
        ],
        "platform_admin_key_ids": result.platform_admin_key_ids,
        "platform_admin_keys": result.platform_admin_keys,
        "sample_k6_keys": sample_k6,
        "catalog_plan_keys": result.catalog_plan_keys,
        "usage_events_accepted": result.usage_events_accepted,
        "recon_invoice_ids": result.recon_invoice_ids,
        "manifest_path": result.manifest_path,
    }


def _apply_mock_stripe_base_url(cli_override: str | None = None) -> None:
    """Set MOCK_STRIPE_BASE_URL for host runs (compose DNS → localhost)."""
    get_settings.cache_clear()
    raw = (
        cli_override
        or os.environ.get("MOCK_STRIPE_BASE_URL")
        or get_settings().mock_stripe_base_url
    )
    resolved = resolve_mock_stripe_base_url(raw)
    os.environ["MOCK_STRIPE_BASE_URL"] = resolved
    get_settings.cache_clear()


async def _run_with_url(
    database_url: str,
    profile_name: str,
    *,
    purge: bool,
    emit_k6: bool,
    mock_stripe_base_url: str | None = None,
) -> SeedResult:
    _apply_mock_stripe_base_url(mock_stripe_base_url)
    engine = create_async_engine(database_url, pool_pre_ping=True)
    session_factory = async_sessionmaker(engine, expire_on_commit=False, class_=AsyncSession)
    settings = get_settings()
    profile = PROFILES[profile_name]

    async with session_factory() as session:
        if purge:
            deleted = await purge_prod_like_prefix(session)
            print(f"purged {deleted} prod-like org(s)", file=sys.stderr)
            await session.commit()

        if profile.dunning_campaigns and not settings.dunning_enabled:
            print(
                "note: profile expects dunning rows but DUNNING_ENABLED is false",
                file=sys.stderr,
            )

        result = await run_prod_like_seed(session, settings, profile)
        await session.commit()

    await engine.dispose()

    seeded_at = datetime.now(UTC).isoformat().replace("+00:00", "Z")
    manifest = _result_to_manifest(result, seeded_at=seeded_at)
    _write_manifest(manifest)
    if emit_k6:
        sample = manifest.get("sample_k6_keys")
        if isinstance(sample, list):
            _write_k6_env([entry for entry in sample if isinstance(entry, dict)])

    summary = {
        "profile": result.profile,
        "organization_count": result.organization_count,
        "recon_organization_count": result.recon_organization_count,
        "organization_count_total": result.organization_count_total,
        "usage_events_accepted": result.usage_events_accepted,
        "usage_events_duplicates": result.usage_events_duplicates,
        "manifest_path": result.manifest_path,
        "catalog_plan_keys": result.catalog_plan_keys,
    }
    print(json.dumps(summary, indent=2))
    return result


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Seed prod-like multi-tenant dataset")
    parser.add_argument(
        "--profile",
        choices=sorted(PROFILES),
        default="medium",
        help="Seed profile (default: medium)",
    )
    parser.add_argument(
        "--database-url",
        default=None,
        help="Postgres URL (default: DATABASE_URL / settings)",
    )
    parser.add_argument(
        "--purge-prod-like-prefix",
        action="store_true",
        help=(
            "Delete prod-like PG slice (pl_ prefix) before seeding; "
            "does not recall Kafka messages"
        ),
    )
    parser.add_argument(
        "--emit-k6-env",
        action="store_true",
        help=f"Write {K6_ENV_PATH}",
    )
    parser.add_argument(
        "--mock-stripe-base-url",
        default=None,
        help="Override mock-stripe base URL (default: MOCK_STRIPE_BASE_URL / settings)",
    )
    return parser.parse_args(argv)


async def main(argv: list[str] | None = None) -> None:
    args = _parse_args(argv)
    _apply_mock_stripe_base_url(args.mock_stripe_base_url)
    settings = get_settings()
    database_url = args.database_url or settings.database_url
    await _run_with_url(
        database_url,
        args.profile,
        purge=args.purge_prod_like_prefix,
        emit_k6=args.emit_k6_env,
        mock_stripe_base_url=args.mock_stripe_base_url,
    )


if __name__ == "__main__":
    asyncio.run(main())
